### ISSUE TITLE
How would one go about integrating gulp-file-include in this boilerplate?

### ISSUE THREAD

**Issue by aligajani** [wapbamboogie/bootstrap-4-boilerplate#9]
https://www.npmjs.com/package/gulp-file-include

I am looking to use the above library for templating.

**Comment by henrikhb** [comment]
I have not worked specifically with gulp-file-include. 
But you would need to install it as per the instructions. 
Then add `require('gulp-file-include')` in the top of the gulpfile.js and add the `gulp.task('fileinclude'..` to the list of gulp tasks.
Then you need to make sure the two tasks `gulp serve` and `gulp ` takes the new task into account by adding it to the array like `gulp.task('serve', ['watchFiles', 'fileinclude'], function(){...` 
That would be how I would start to go about it but cannot provide more details since I have not used it.
